server:
  port: 8888

spring:
  application:
    name: letterbox
  datasource:
    url: jdbc:mysql://localhost:3306/letterbox?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  output:
    ansi:
      enabled: ALWAYS

#logging:
#  file:
#    name: application.log
#  level:
#    org:
#      springframework:
#        security: DEBUG





