server:
  port: 8888

spring:
  application:
    name: letterbox
  datasource:
    url: jdbc:mysql://database-2.c9mmqgsmok4e.ap-south-1.rds.amazonaws.com/letterbox?createDatabaseIfNotExist=true
    username: admin #root
    password: UYq343ZtAi9r4w7gKHPm #password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  output:
    ansi:
      enabled: ALWAYS

#logging:
#  file:
#    name: application.log
#  level:
#    org:
#      springframework:
#        security: DEBUG





